SET(CPP_FILES 
  rttbBioModel.cpp
  rttbBioModelCurve.cpp
  rttbBioModelScatterPlots.cpp
  rttbNTCPLKBModel.cpp
  rttbNTCPRSModel.cpp
  rttbTCPModel.cpp
  rttbTCPLQModel.cpp
  rttbDvhBasedModels.cpp
  rttbIntegration.cpp
  )

SET(H_FILES 
  rttbBaseTypeModels.h
  rttbBioModel.h
  rttbBioModelCurve.h
  rttbBioModelScatterPlots.h
  rttbNTCPModel.h
  rttbNTCPLKBModel.h
  rttbNTCPRSModel.h
  rttbTCPModel.h
  rttbTCPLQModel.h  
  rttbDvhBasedModels.h
  rttbIntegration.h
)
