SET(CPP_FILES 
	rttbOTBMaskAccessor.cpp
	rttbMask.cpp
	DoseVoxel_LEGACY.cpp
	DoseIteratorInterface_LEGACY.cpp
	DoseIterator_LEGACY.cpp
	rttbContour_LEGACY.cpp
	rttbIterativePolygonInTermsOfIntersections_LEGACY.cpp
	rttbPolygonInfo_LEGACY.cpp
	rttbSelfIntersectingStructureException.cpp
	rttbStructure_LEGACY.cpp
	rttbGenericMutableMaskAccessor.cpp
  )

SET(H_FILES 
	rttbMaskType_LEGACY.h
	rttbMask.h
	rttbOTBMaskAccessor.h
	DoseVoxel_LEGACY.h
	DoseIteratorInterface_LEGACY.h
	DoseIterator_LEGACY.h
	rttbContour_LEGACY.h
	rttbIterativePolygonInTermsOfIntersections_LEGACY.h
	rttbField_LEGACY.h
	rttbPolygonInfo_LEGACY.h
	rttbBaseType_LEGACY.h
	rttbSelfIntersectingStructureException.h
	rttbStructure_LEGACY.h
	rttbGenericMutableMaskAccessor.h
)
