SET(CPP_FILES 
	DummyDoseAccessor.cpp
	DummyInhomogeneousDoseAccessor.cpp
	DummyMaskAccessor.cpp
	DummyMutableDoseAccessor.cpp
	DummyDVHGenerator.cpp
	DummyStructure.cpp
	CreateTestStructure.cpp	
  )

SET(H_FILES 
	DummyStructure.h
	DummyDoseAccessor.h
	DummyInhomogeneousDoseAccessor.h
	DummyMaskAccessor.h
	DummyMutableDoseAccessor.h
	DummyDVHGenerator.h
	CreateTestStructure.h
)
