#use postgresql
#if using Win64 generator
IF(CMAKE_CL_64)
  SET(POSTGRESQL_DIR ${RTToolbox_SOURCE_DIR}/../PostgreSQL-8.4-64)
ELSE()
  SET(POSTGRESQL_DIR ${RTToolbox_SOURCE_DIR}/../postgresql-8.3.8-1) 
ENDIF(CMAKE_CL_64)

LIST(APPEND ALL_INCLUDE_DIRECTORIES ${POSTGRESQL_DIR}/include)

IF(CMAKE_CL_64)
  LIST(APPEND ALL_LIBRARIES libpq libpqdll)
ELSE()
  LIST(APPEND ALL_LIBRARIES libpq)
ENDIF(CMAKE_CL_64)

LINK_DIRECTORIES(${POSTGRESQL_DIR}/lib) 
