IF(NOT Boost_FOUND)

  IF(DEFINED Boost_INCLUDE_DIR)
    IF(NOT IS_ABSOLUTE ${Boost_INCLUDE_DIR})
      SET(Boost_INCLUDE_DIR "${RTToolbox_BINARY_DIR}/${Boost_INCLUDE_DIR}")
    ENDIF(NOT IS_ABSOLUTE ${Boost_INCLUDE_DIR})
  ENDIF(DEFINED Boost_INCLUDE_DIR)

  SET(BOOST_MIN_VERSION "1.64.0")
  FIND_PACKAGE(Boost ${BOOST_MIN_VERSION} REQUIRED QUIET)

  LIST(APPEND ALL_INCLUDE_DIRECTORIES ${Boost_INCLUDE_DIRS})
	
  MARK_AS_ADVANCED(CLEAR Boost_INCLUDE_DIR)
	
ENDIF(NOT Boost_FOUND)

