SET(CPP_FILES 
  rttbConformalIndex.cpp
  rttbConformationNumber.cpp
  rttbConformityIndex.cpp
  rttbCoverageIndex.cpp
  rttbDoseIndex.cpp
  rttbDvhBasedDoseIndex.cpp
  rttbHomogeneityIndex.cpp
  )

SET(H_FILES 
  rttbConformalIndex.h
  rttbConformationNumber.h
  rttbConformityIndex.h
  rttbCoverageIndex.h
  rttbDoseIndex.h
  rttbDvhBasedDoseIndex.h
  rttbHomogeneityIndex.h
)
