SET(CPP_FILES 
  rttbAccessorWithGeoInfoBase.cpp
  rttbDoseIteratorInterface.cpp
  rttbDVH.cpp
  rttbDVHCalculator.cpp
  rttbDVHSet.cpp
  rttbGenericDoseIterator.cpp
  rttbGenericMaskedDoseIterator.cpp
  rttbGeometricInfo.cpp
  rttbMaskedDoseIteratorInterface.cpp
  rttbMaskVoxel.cpp
  rttbStructure.cpp
  rttbStructureSet.cpp
  rttbStrVectorStructureSetGenerator.cpp
  rttbUtils.cpp
  rttbMutableMaskAccessorInterface.cpp
  )

SET(H_FILES 
  rttbAccessorInterface.h
  rttbAccessorWithGeoInfoBase.h
  rttbBaseType.h
  rttbDataNotAvailableException.h
  rttbDoseAccessorInterface.h
  rttbDoseIteratorInterface.h
  rttbDoseAccessorGeneratorBase.h
  rttbDoseAccessorGeneratorInterface.h
  rttbDVH.h
  rttbDVHCalculator.h
  rttbDVHGeneratorInterface.h
  rttbDVHSet.h
  rttbException.h
  rttbExceptionMacros.h
  rttbGenericDoseIterator.h
  rttbGenericMaskedDoseIterator.h
  rttbGeometricInfo.h
  rttbIndexConversionInterface.h
  rttbIndexOutOfBoundsException.h
  rttbInvalidDoseException.h
  rttbInvalidParameterException.h
  rttbMappingOutsideOfImageException.h
  rttbMaskAccessorGeneratorBase.h
  rttbMaskAccessorGeneratorInterface.h
  rttbMaskAccessorInterface.h
  rttbMaskAccessorProcessorBase.h
  rttbMaskAccessorProcessorInterface.h
  rttbMaskedDoseIteratorInterface.h
  rttbMaskVoxel.h
  rttbMutableDoseAccessorInterface.h
  rttbMutableMaskAccessorInterface.h
  rttbNullPointerException.h
  rttbPaddingException.h
  rttbStructure.h
  rttbStructureSet.h
  rttbStructureSetGeneratorInterface.h
  rttbStrVectorStructureSetGenerator.h
  rttbUtils.h
  rttbCommon.h
)
