SET(CPP_FILES 
  rttbAccessorWithGeoInfoBase.cpp
  rttbDoseIteratorInterface.cpp
  rttbDVH.cpp
  rttbDVHCalculator.cpp
  rttbDVHSet.cpp
  rttbDataNotAvailableException.cpp
  rttbException.cpp		
  rttbGenericDoseIterator.cpp
  rttbGenericMaskedDoseIterator.cpp
  rttbGeometricInfo.cpp
  rttbIndexOutOfBoundsException.cpp
  rttbInvalidDoseException.cpp
  rttbInvalidParameterException.cpp
  rttbMappingOutsideOfImageException.cpp
  rttbMaskedDoseIteratorInterface.cpp
  rttbMaskVoxel.cpp
  rttbNullPointerException.cpp
  rttbPaddingException.cpp
  rttbStructure.cpp
  rttbStructureSet.cpp
  rttbStrVectorStructureSetGenerator.cpp
  )

SET(H_FILES 
  rttbAccessorInterface.h
  rttbAccessorWithGeoInfoBase.h
  rttbBaseType.h
  rttbDataNotAvailableException.h
  rttbDoseAccessorInterface.h
  rttbDoseIteratorInterface.h
  rttbDoseAccessorGeneratorBase.h
  rttbDoseAccessorGeneratorInterface.h
  rttbDVH.h
  rttbDVHCalculator.h
  rttbDVHGeneratorInterface.h
  rttbDVHSet.h
  rttbException.h
  rttbExceptionMacros.h
  rttbGenericDoseIterator.h
  rttbGenericMaskedDoseIterator.h
  rttbGeometricInfo.h
  rttbIndexConversionInterface.h
  rttbIndexOutOfBoundsException.h
  rttbInvalidDoseException.h
  rttbInvalidParameterException.h
  rttbMappingOutsideOfImageException.h
  rttbMaskAccessorGeneratorBase.h
  rttbMaskAccessorGeneratorInterface.h
  rttbMaskAccessorInterface.h
  rttbMaskAccessorProcessorBase.h
  rttbMaskAccessorProcessorInterface.h
  rttbMaskedDoseIteratorInterface.h
  rttbMaskVoxel.h
  rttbMutableDoseAccessorInterface.h
  rttbMutableMaskAccessorInterface.h
  rttbNullPointerException.h
  rttbPaddingException.h
  rttbStructure.h
  rttbStructureSet.h
  rttbStructureSetGeneratorInterface.h
  rttbStrVectorStructureSetGenerator.h
)
