SET(CPP_FILES 
  rttbDcmrtException.cpp
  rttbDicomDoseAccessor.cpp
  rttbDicomFileDoseAccessorGenerator.cpp
  rttbDicomFileReaderHelper.cpp
  rttbDicomFileStructureSetGenerator.cpp
  rttbDicomIODDoseAccessorGenerator.cpp
  rttbDicomIODStructureSetGenerator.cpp
  rttbDVHDicomFileReader.cpp
  )

SET(H_FILES 
  rttbDcmrtException.h
  rttbDicomDoseAccessor.h
  rttbDicomFileDoseAccessorGenerator.h
  rttbDicomFileReaderHelper.h
  rttbDicomFileStructureSetGenerator.h
  rttbDicomIODDoseAccessorGenerator.h
  rttbDicomIODStructureSetGenerator.h
  rttbDVHDicomFileReader.h
)
