SET(CPP_FILES 
	rttbBoostMask.cpp
	rttbBoostMaskAccessor.cpp
	rttbITKImageFileMaskAccessorGenerator.cpp
	rttbITKImageMaskAccessor.cpp
	rttbITKImageMaskAccessorGenerator.cpp
	rttbITKImageMaskAccessorConverter.cpp
  )

SET(H_FILES 
	rttbBoostMask.h
	rttbBoostMaskAccessor.h
	rttbITKImageFileMaskAccessorGenerator.h
	rttbITKImageMaskAccessor.h
	rttbITKImageMaskAccessorGenerator.h
	rttbITKImageMaskAccessorConverter.h
	rttbMaskAccessorProcessorBase.h
	rttbMaskAccessorProcessorInterface.h
	../itk/rttbImageReader.h
	../itk/rttbImageReader.tpp
	../itk/rttbITKIOHelper.h
	../itk/rttbITKIOHelper.tpp
)
