SET(CPP_FILES 
	rttbFileDispatch.cpp
	rttbGenericImageReader.cpp
	rttbImageWriter.cpp
	rttbITKImageDoseAccessor.cpp
	rttbITKImageDoseAccessorConverter.cpp
	rttbITKImageDoseAccessorGenerator.cpp
	rttbITKImageFileDoseAccessorGenerator.cpp
	rttbITKImageFileMaskAccessorGenerator.cpp
	rttbITKImageMaskAccessor.cpp
	rttbITKImageMaskAccessorGenerator.cpp
	rttbITKImageMaskAccessorConverter.cpp
	rttbITKIOHelper.cpp
  )

SET(H_FILES 
	rttbDoseAccessorConversionSettingInterface.h
	rttbDoseAccessorProcessorBase.h
	rttbDoseAccessorProcessorInterface.h
	rttbFileDispatch.h
	rttbGenericImageReader.h
	rttbImageReader.h
	rttbImageReader.tpp
	rttbImageWriter.h
	rttbITKImageDoseAccessor.h
	rttbITKImageDoseAccessorConverter.h
	rttbITKImageDoseAccessorGenerator.h
	rttbITKImageFileDoseAccessorGenerator.h
	rttbITKImageFileMaskAccessorGenerator.h
	rttbITKImageMaskAccessor.h
	rttbITKImageMaskAccessorConverter.h
	rttbITKImageMaskAccessorGenerator.h
	rttbITKIOHelper.h
	rttbITKIOHelper.tpp

)
