SET(CPP_FILES 
	rttbFileDispatch.cpp
	rttbGenericImageReader.cpp
	rttbImageWriter.cpp
	rttbITKException.cpp
	rttbITKImageAccessor.cpp
	rttbITKImageAccessorConverter.cpp
	rttbITKImageAccessorGenerator.cpp
	rttbITKImageFileAccessorGenerator.cpp
	rttbITKImageFileMaskAccessorGenerator.cpp
	rttbITKImageMaskAccessor.cpp
	rttbITKImageMaskAccessorGenerator.cpp
	rttbITKImageMaskAccessorConverter.cpp
	rttbITKIOHelper.cpp
  )

SET(H_FILES 
	rttbDoseAccessorConversionSettingInterface.h
	rttbDoseAccessorProcessorBase.h
	rttbDoseAccessorProcessorInterface.h
	rttbFileDispatch.h
	rttbGenericImageReader.h
	rttbImageReader.h
	rttbImageReader.tpp
	rttbImageWriter.h
	rttbITKException.h
	rttbITKImageAccessor.h
	rttbITKImageAccessorConverter.h
	rttbITKImageAccessorGenerator.h
	rttbITKImageFileAccessorGenerator.h
	rttbITKImageFileMaskAccessorGenerator.h
	rttbITKImageMaskAccessor.h
	rttbITKImageMaskAccessorConverter.h
	rttbITKImageMaskAccessorGenerator.h
	rttbITKIOHelper.h
	rttbITKIOHelper.tpp

)
