SET(CPP_FILES 
	rttbITKImageDoseAccessor.cpp
	rttbITKImageFileDoseAccessorGenerator.cpp
	rttbITKImageDoseAccessorGenerator.cpp
	rttbGenericImageReader.cpp
	rttbFileDispatch.cpp
	rttbITKImageDoseAccessorConverter.cpp
  )

SET(H_FILES 
	rttbITKImageDoseAccessor.h
	rttbITKImageFileDoseAccessorGenerator.h
	rttbITKImageFileDoseAccessorGenerator.tpp
	rttbITKImageDoseAccessorGenerator.h
	rttbGenericImageReader.h
	rttbImageReader.h
	rttbImageReader.tpp
	rttbFileDispatch.h
	rttbITKImageDoseAccessorConverter.h
	rttbDoseAccessorProcessorInterface.h
	rttbDoseAccessorProcessorBase.h
	rttbDoseAccessorConversionSettingInterface.h
)
